FAO43166:
  method: AluI_MboI 
  cell_line: HelaLT
  basecall_version: 4.0.11
  basecall_model: hac
  kit: LSK-109
  pore: r9.4
  user: DD
      
PAF13971:
  method: AluI_MboI 
  cell_line: HelaLT
  basecall_version: 4.0.11
  basecall_model: hac
  kit: LSK-109
  pore: r9.4
  user: DD

FAO43198:
  method: AluI_MboI 
  cell_line: HelaVST
  basecall_version: 4.0.11
  basecall_model: hac
  kit: LSK-109
  pore: r9.4
  user: DD

PAF05879:
  method: AluI_MboI 
  cell_line: HelaVST
  basecall_version: 4.0.11
  basecall_model: hac
  kit: LSK-109
  pore: r9.4
  user: DD

PAF14730:
  method: AluI_MboI 
  cell_line: HelaVST
  basecall_version: 4.0.11
  basecall_model: hac 
  kit: LSK-109
  pore: r9.4
  user: DD

FAO47403:
  method: sheared_adaptive
  cell_line: HelaVST
  basecall_version: 4.2.2
  basecall_model: hac
  kit: LSK-109
  pore: r9.4
  user: CT

FAO31810: 
  method: sheared_adaptive
  cell_line: HelaLT
  basecall_version: 4.2.2
  basecall_model: hac
  kit: LSK-109
  pore: r9.4
  user: CT

FAO38606:
  method: sheared_control
  cell_line: HelaVST
  basecall_version: 4.2.3
  basecall_model: hac
  kit: LSK-109
  pore: r9.4
  user: CT

FAO46943:
  method: sheared_control
  cell_line: HelaLT
  basecall_version: 4.2.3
  basecall_model: fast
  kit: LSK-109
  pore: r9.4
  user: CT

FAO72457:
  method: read_fish
  cell_line: HelaLT
  basecall_version: 4.2.2
  basecall_model: hac
  kit: LSK-109
  pore: r9.4
  user: CT


FAO44072:
  method: AluI_MboI
  cell_line: HelaVST
  basecall_version: 4.2.3
  basecall_model: hac
  kit: LSK-109  
  pore: r10.3
  user: CT

FAO43849:
  method: AluI_MboI
  cell_line: HelaLT
  basecall_version: 4.2.3
  basecall_model: hac
  kit: LSK-109
  pore: r10.3
  user: CT

FAO44146:
  method: AluI_MboI
  cell_line: HG002
  basecall_version: 4.2.3
  basecall_model: hac
  kit: LSK-109
  pore: r10.3
  user: CT

FAP57752:
  method: AluI_MboI
  cell_line: HG002
  basecall_version: 4.2.3
  basecall_model: hac
  kit: LSK-109
  pore: r9.4
  user: CT
  pore_count: 1347

FAP57087:
  method: sheared_adaptive
  cell_line: HG002
  basecall_version: 4.2.3
  basecall_model: hac
  kit: LSK-109
  pore: r9.4
  user: CT
 
FAP51440:
  method: ApoI_PvuII
  cell_line: HG002
  basecall_version: 4.2.3
  basecall_model: hac
  kit: LSK-110
  pore: r9.4
  user: CT
  pore_count: 1139 

FAQ05173:
  method: BamHI-HF 
  cell_line: HG002
  basecall_version: 4.3.4
  basecall_model: hac
  kit: LSK-110
  pore: r9.4
  user: CT
  pore_count: 1418

FAQ02475:
  method: ECoRV-HF
  cell_line: HG002
  basecall_version: 4.3.4
  basecall_model: hac
  kit: LSK-110
  pore: r9.4
  user: CT
  pore_count: 1417

FAQ39601:
    method: cas9_00
    cell_line: HG002
    basecall_version: 4.3.4
    basecall_model: hac
    kit: LSK-110
    pore: r9.4
    user: CT
    pore_count: 1377

FAQ06106:
    method: tail_seq00_control
    cell_line: HG002
    basecall_version: 4.3.4
    basecall_model: hac
    kit: LSK-110
    pore: r9.4
    user: CT
    pore_count: 1056

FAQ36983:
    method: tailseq00
    cell_line: HG002
    basecall_version: 4.3.4
    basecall_model: hac
    kit: LSK-110
    pore: r9.4
    user: CT
    pore_count: 1254

FAQ06292:
    method: control_sheard15kb 
    cell_line: HG002
    basecall_version: 4.3.4
    basecall_model: hac
    kit: LSK-110
    pore: r9.4
    user: CT
    starting_conc: 1ug
    final_conc: 120ng 
    pore_count: 1186


FAQ44376:
    method: tailseq00_cas9_00
    cell_line: HG002
    basecall_version: 4.3.4
    basecall_model: hac
    kit: LSK-110
    pore: r9.4
    user: CT
    starting_conc: 3ug + 3ug
    final_conc: 3ug
    pore_count: 1396

FAQ41420:
    method: cas9_01
    cell_line: HG002
    basecall_version: 4.3.4
    basecall_model: hac
    kit: LSK-110
    pore: r9.4
    user: CT
    starting_conc: 3ug
    final_conc: 425ng
    pore_count: 1399

FAQ41387:
    method: tailseq01_bamHI
    cell_line: HG002
    basecall_version: 4.3.4
    basecall_model: hac
    kit: LSK-110
    pore: r9.4
    user: CT
    starting_conc: 3ug
    final_conc: 284ng
    pore_count: 1436

FAO47403:
    method: multiplex_cas902
    cell_line: HG002
    basecall_version: 4.3.4
    basecall_model: hac
    kit: LSK-110
    pore: r9.4
    user: CT
    starting_conc: 5ug
    final_conc: 284ng
    pore_count: 1436
